import torch

from enum import IntEnum

from data.utils import get_logger
from data.base import Process
from data.serialised_process import SerialisedProcess
from data.prompter import Prompter, SummarizationPrompt

logger = get_logger(__name__)


class SummarizeMethodEnum(IntEnum):
    NONE = 0
    HF_PROMPT = 1


class SummarizeMethod:
    def __init__(self, method, *args, **kwargs):
        if isinstance(method, str):
            method = SummarizeMethodEnum[method.upper()]
        else:
            method = SummarizeMethodEnum(method)

        if method == SummarizeMethodEnum.NONE:
            self.method = None
        elif method == SummarizeMethodEnum.HF_PROMPT:
            self.method = Prompter(SummarizationPrompt(), *args, **kwargs)

    def __call__(self, raw_content, tokenizer=None, *args, **kwargs):
        assert tokenizer is not None

        content = tokenizer.decode(raw_content["input_ids"])
        if self.method is None:
            return content

        item = self.method(content, *args, **kwargs)
        ret = tokenizer(item, return_tensors="pt") if tokenizer is not None else item
        for key in ret.keys():
            ret[key] = ret[key].squeeze(0)
        assert "input_ids" in ret.keys() and ret["input_ids"].dim() == 1, ret

        ret["token_type_ids"] = torch.zeros_like(ret["input_ids"])
        ret["other_token_type_ids"] = torch.zeros_like(ret["input_ids"])
        ret["timings"] = torch.ones(ret["input_ids"].shape[0], 2) * -1
        ret["turn_ids"] = torch.zeros_like(ret["input_ids"])
        ret["loss_mask"] = (
            torch.ones_like(ret["input_ids"]) * raw_content["loss_mask"][0].item()
        )

        return ret


class FutureContextProcess(Process):
    def __init__(
        self,
        tokenizer,
        split_utt=True,
        max_length=256,
        keep_length=64,
        overlap_length=10,
        summarize_method=SummarizeMethod(
            SummarizeMethodEnum.NONE, "meta-llama/Llama-3.2-3B-Instruct"
        ),
        **kwargs,
    ):
        super().__init__(tokenizer)

        self.split_utt = split_utt
        self.max_length = max_length

        self.summarize_method = summarize_method

        self.serialised_processor = SerialisedProcess(
            tokenizer=tokenizer,
            split_utt=False,
            combine_speaker=True,
            max_length=max_length,
            keep_length=keep_length,
            overlap_length=overlap_length,
            remove_special_tokens=True,
        )

    def __hash__(self):
        return hash(self.__str__())

    def __str__(self):
        return "FutureContextProcess"

    def __repr__(self):
        return self.__str__()

    def config_to_dict(self):
        return {
            "split_utt": self.split_utt,
            "max_length": self.max_length,
            "keep_length": self.serialised_processor.keep_length,
            "overlap_length": self.serialised_processor.overlap_length,
            "summarize_method": self.summarize_method,
        }

    def process(self, datasets=[], in_parallel=False, _misc=0):
        for parent_ds in datasets:
            dss, start, batch_size = parent_ds
            for ds in dss.get_batch(start, batch_size):
                for conv in self.serialised_processor.process_conversation(ds):
                    for processed_conv in self._process_conv(conv):
                        yield processed_conv

    def _process_conv(self, conv):
        """
        Convert the conversation generated by the serialised processor into the convesational history, response and the future context.
        We should generate samples for each turn in the conversation.
        The future context is only the future context of one speaker

        Args:
            conv (dict): The conversation generated by the serialised processor.
                            It contains the keys `speakerA' and `turns'
        """

        for _, turn in enumerate(conv["turns"]):
            start_idx, end_idx = self._find_turn_indices(turn, conv["speakerA"])

            history = self._extract_dialogue(conv["speakerA"], end_idx=end_idx)
            current_utterance = self._extract_dialogue(
                conv["speakerA"], start_idx, end_idx + 1
            )
            future_context = self._get_future_context(
                conv["speakerA"],
                speaker=conv["speakerA"]["speaker_ids"][start_idx],
            )

            if future_context["input_ids"].shape[0] == 0:
                logger.error(
                    f"Future context is empty. Skipping the turn {turn} in the conversation {conv}"
                )
                continue

            item = self._format_sample(
                history=history,
                current_utterance=current_utterance,
                future_context=future_context,
            )
            if item is None:
                continue

            yield {"speakerA": item, "turns": conv["turns"]}

    def _add_boundary_tags(
        self,
        conv,
        start_token: dict[str, torch.Tensor],
        end_token: dict[str, torch.Tensor],
    ):
        """
        Add boundary tags to the conversation.

        Args:
            conv (dict): The conversation
            start_token (dict): The start token
            end_token (dict): The end token
        """

        conv["input_ids"] = torch.cat(
            [start_token["input_ids"], conv["input_ids"], end_token["input_ids"]]
        )
        conv["attention_mask"] = torch.cat(
            [
                start_token["attention_mask"],
                conv["attention_mask"],
                end_token["attention_mask"],
            ]
        )
        conv["speaker_ids"] = torch.cat(
            [
                start_token["speaker_ids"],
                conv["speaker_ids"],
                end_token["speaker_ids"],
            ]
        )
        conv["token_type_ids"] = torch.cat(
            [
                torch.zeros_like(start_token["input_ids"]),
                conv["token_type_ids"],
                torch.zeros_like(end_token["input_ids"]),
            ]
        )
        conv["other_token_type_ids"] = torch.cat(
            [
                torch.zeros_like(start_token["input_ids"]),
                conv["other_token_type_ids"],
                torch.zeros_like(end_token["input_ids"]),
            ]
        )
        conv["timings"] = torch.cat(
            [
                torch.ones(start_token["input_ids"].shape[0], 2) * -1,
                conv["timings"],
                torch.ones(end_token["input_ids"].shape[0], 2) * -1,
            ]
        )
        conv["turn_ids"] = torch.cat(
            [
                torch.zeros_like(start_token["input_ids"]),
                conv["turn_ids"],
                torch.zeros_like(end_token["input_ids"]),
            ]
        )
        conv["loss_mask"] = torch.cat(
            [
                torch.ones_like(start_token["input_ids"]),
                conv["loss_mask"],
                torch.ones_like(end_token["input_ids"]),
            ]
        )

        return conv

    def _format_sample(
        self, history, current_utterance, future_context, start_idx=0, end_idx=None
    ):
        """
        Format the sample for the future context task.

        Args:
            history (dict): The conversation history
            current_utterance (dict): The current utterance
            future_context (dict): The future context
            start_idx (int): The start index of the current utterance
            end_idx (int): The end index of the current utterance
        """
        # Limit the length of the sample to `max_length'.
        # Current Utterance should remain
        # Future context should remain the same, if required truncate so that remaining length is split evenly with history
        # History should remain the same, if required truncate so that remaining length is split evenly with future context
        # Loss mask should mask the future context and history
        curr_utterance_length = current_utterance["input_ids"].shape[0]
        future_context_length = future_context["input_ids"].shape[0]
        history_length = history["input_ids"].shape[0]

        if (
            curr_utterance_length + future_context_length + history_length
            > self.max_length
        ):
            remaining_length = self.max_length - curr_utterance_length
            if remaining_length % 2 != 0:
                remaining_length -= 1

            if remaining_length < 0:
                logger.error("The remaining length is negative. Skipping the sample")
                return None

            utterance_length = remaining_length // 2

            history = self._extract_dialogue(
                history, start_idx=start_idx - utterance_length, end_idx=start_idx
            )
            future_context = self._extract_dialogue(
                future_context, start_idx=0, end_idx=utterance_length
            )
            future_context = self.summarize_method(
                future_context,
                tokenizer=self.tokenizer,
            )

        for key in history.keys():
            if isinstance(history[key], torch.Tensor):
                history[key] = torch.cat([history[key], current_utterance[key]])

        # Add tag to boundaries of history
        start_token = {
            k: torch.tensor(v) for k, v in self.tokenizer("<convseration>").items()
        }
        end_token = {
            k: torch.tensor(v) for k, v in self.tokenizer("</convseration>").items()
        }
        history = self._add_boundary_tags(history, start_token, end_token)

        # Add tag to boundaries of future context
        start_token = {
            k: torch.tensor(v) for k, v in self.tokenizer("<future_context>").items()
        }
        end_token = {
            k: torch.tensor(v) for k, v in self.tokenizer("</future_context>").items()
        }
        future_context = self._add_boundary_tags(future_context, start_token, end_token)

        output = {k: v for k, v in future_context.items()}
        for key in output.keys():
            if isinstance(output[key], torch.Tensor):
                output[key] = torch.cat([output[key], history[key]])

        return output

    def _extract_dialogue(self, conv, start_idx=0, end_idx=None, mask=None):
        if end_idx is None:
            end_idx = len(conv["input_ids"])
        if mask is None:
            mask = torch.ones_like(conv["input_ids"])[start_idx:end_idx].bool()
        else:
            mask = mask[start_idx:end_idx]

        assert mask.dtype == torch.bool

        return {
            "input_ids": conv["input_ids"][start_idx:end_idx][mask],
            "attention_mask": conv["attention_mask"][start_idx:end_idx][mask],
            "speaker_ids": conv["speaker_ids"][start_idx:end_idx][mask],
            "token_type_ids": conv["token_type_ids"][start_idx:end_idx][mask],
            "other_token_type_ids": conv["other_token_type_ids"][start_idx:end_idx][
                mask
            ],
            "timings": conv["timings"][start_idx:end_idx][mask],
            "turn_ids": conv["turn_ids"][start_idx:end_idx][mask],
            "loss_mask": conv["loss_mask"][start_idx:end_idx][mask],
            "conv_id": conv["conv_id"],
        }

    def _get_future_context(self, conv, speaker=None):
        """
        Get the future context of the speaker in the conversation.
        TODO: Add the option to only get the future context of the current speaker

        Args:
            conv (dict): The conversation generated. It contains the keys `timings', `input_ids', `speaker_ids'
            speaker (int): The speaker for whom we want to get the future context. If set to `None', we get the future context of both speakers.
            current_utterance (tuple): The start and end indices of the current utterance in the conversation.
        """

        if speaker is None:
            speaker_mask = torch.ones_like(conv["speaker_ids"])
        else:
            speaker_mask = torch.eq(conv["speaker_ids"], speaker)

        item = self._extract_dialogue(conv, mask=speaker_mask)
        item["loss_mask"] *= 0

        return item

    def _find_turn_indices(self, turn, speakerA):
        """
        Find the start and end indices of the turn in the conversation history.

        Args:
            turn (dict): The turn for which we want to find the indices
            speakerA (dict): The speakerA in the conversation
        """

        start_idx = 0
        end_idx = 0

        timings = speakerA["timings"]
        start_idx_possible = torch.nonzero(
            torch.eq(timings, turn["start"]), as_tuple=True
        )[0]
        end_idx_possible = torch.nonzero(torch.eq(timings, turn["end"]), as_tuple=True)[
            0
        ]

        if len(start_idx_possible) == 0 or len(end_idx_possible) == 0:
            raise ValueError("Could not find the start or end index of the turn")

        if len(start_idx_possible) != 1 or len(end_idx_possible) != 1:
            raise ValueError("Multiple possible start or end indices found")

        start_idx = start_idx_possible[0].item()
        end_idx = end_idx_possible[0].item()
        return start_idx, end_idx
